export const TOPASSET_GET_REQUEST = "TOPASSET_GET_REQUEST";
export const TOPASSET_GET_SUCCESS = "TOPASSET_GET_SUCCESS";
export const TOPASSET_GET_FAIL = "TOPASSET_GET_FAIL";

export const ASSET_ADD_REQUEST = "ASSET_ADD_REQUEST";
export const ASSET_ADD_SUCCESS = "ASSET_ADD_SUCCESS";
export const ASSET_ADD_FAIL = "ASSET_ADD_FAIL";

export const ASSET_DELETE_REQUEST = "ASSET_DELETE_REQUEST";
export const ASSET_DELETE_SUCCESS = "ASSET_DELETE_SUCCESS";
export const ASSET_DELETE_FAIL = "ASSET_DELETE_FAIL";

export const ASSET_DIALOG_OPEN = "ASSET_DIALOG_OPEN";
