export const PORTFOLIO_LIST_REQUEST = "PORTFOLIO_LIST_REQUEST";
export const PORTFOLIO_LIST_SUCCESS = "PORTFOLIO_LIST_SUCCESS";
export const PORTFOLIO_LIST_FAIL = "PORTFOLIO_LIST_FAIL";
export const CALC_PORTFOLIO = "CALC_PORTFOLIO";

export const PORTFOLIO_ADD_REQUEST = "PORTFOLIO_ADD_REQUEST";
export const PORTFOLIO_ADD_SUCCESS = "PORTFOLIO_ADD_SUCCESS";
export const PORTFOLIO_ADD_FAIL = "PORTFOLIO_ADD_FAIL";

export const PORTFOLIO_ASSET_ADD_REQUEST = "PORTFOLIO_ASSET_ADD_REQUEST ";
export const PORTFOLIO_ASSET_ADD_SUCCESS = "PORTFOLIO_ASSET_ADD_SUCCESS";
export const PORTFOLIO_ASSET_ADD_FAIL = "PORTFOLIO_ASSET_ADD_FAIL";

export const PORTFOLIO_ASSET_EDIT_REQUEST = "PORTFOLIO_ASSET_EDIT_REQUEST";
export const PORTFOLIO_ASSET_EDIT_SUCCESS = "PORTFOLIO_ASSET_EDIT_SUCCESS";
export const PORTFOLIO_ASSET_EDIT_FAIL = "PORTFOLIO_ASSET_EDIT_FAIL";

export const PORTFOLIO_DELETE_ASSETS_REQUEST =
  "PORTFOLIO_DELETE_ASSETS_REQUEST";
export const PORTFOLIO_DELETE_ASSETS_SUCCESS =
  "PORTFOLIO_DELETE_ASSETS_SUCCESS";
export const PORTFOLIO_DELETE_ASSETS_FAIL = "PORTFOLIO_DELETE_ASSETS_FAIL";
export const REMOVE_CUD_STATE = "REMOVE_CUD_STATE";
