export const TRANSACTION_ADD_REQUEST = "TRANSACTION_ADD_REQUEST";
export const TRANSACTION_ADD_SUCCESS = "TRANSACTION_ADD_SUCCESS";
export const TRANSACTION_ADD_FAIL = "TRANSACTION_ADD_FAIL";
export const TRANSACTION_INFO_REQUEST = "TRANSACTION_INFO_REQUEST";
export const TRANSACTION_INFO_SUCCESS = "TRANSACTION_INFO_SUCCESS";
export const TRANSACTION_INFO_FAIL = "TRANSACTION_INFO_FAIL";
