export const WATCHLIST_ASSET_ADD_REQUEST = "WATCHLIST_ASSET_ADD_REQUEST";
export const WATCHLIST_ASSET_ADD_SUCCESS = "WATCHLIST_ASSET_ADD_SUCCESS";
export const WATCHLIST_ASSET_ADD_FAIL = "WATCHLIST_ASSET_ADD_FAIL";

export const WATCHLIST_LIST_REQUEST = "WATCHLIST_LIST_REQUEST";
export const WATCHLIST_LIST_SUCCESS = "WATCHLIST_LIST_SUCCESS";
export const WATCHLIST_LIST_FAIL = "WATCHLIST_LIST_FAIL";

export const WATCHLIST_ASSET_EDIT_REQUEST = "WATCHLIST_ASSET_EDIT_REQUEST";
export const WATCHLIST_ASSET_EDIT_SUCCESS = "WATCHLIST_ASSET_EDIT_SUCCESS";
export const WATCHLIST_ASSET_EDIT_FAIL = "WATCHLIST_ASSET_EDIT_FAIL";
export const WATCHLIST_DELETE_ASSETS_REQUEST =
  "WATCHLIST_DELETE_ASSETS_REQUEST";
export const WATCHLIST_DELETE_ASSETS_SUCCESS =
  "WATCHLIST_DELETE_ASSETS_SUCCESS";
export const WATCHLIST_DELETE_ASSETS_FAIL = "WATCHLIST_DELETE_ASSETS_FAIL";
