const formFields = {
  watchlist: {
    add: [
      {
        name: "name",
        label: "Name",
        type: "Asset",
        inputType: "text",
        size: "medium",
        id: "name",
      },
      {
        name: "customType",
        label: "Describe asset",
        type: "Dropdown",
        inputType: "select",
        menuItems: ["Speculation", "Dividend", "Value", "Index", "N/A"],
        defaultSelect: "N/A",
        size: "small",
        id: "customType",
      },
      {
        name: "targetPrice",
        label: "Target price",
        type: "Number",
        inputType: "number",
        size: "small",
        id: "targetPrice",
      },
      {
        name: "comment",
        label: "Comment",
        type: "Text",
        inputType: "text",
        size: "medium",
        id: "comment",
      },
    ],
    edit: [
      {
        name: "name",
        label: "Asset",
        type: "Text",
        inputType: "text",
        size: "medium",
        id: "name",
      },
      {
        name: "customType",
        label: "Describe asset",
        type: "Dropdown",
        inputType: "select",
        menuItems: ["Speculation", "Dividend", "Value", "Index", "N/A"],
        defaultSelect: "N/A",
        size: "small",
        id: "customType",
      },
      {
        name: "targetPrice",
        label: "Target price",
        type: "Number",
        inputType: "number",
        size: "small",
        id: "targetPrice",
      },
      {
        name: "comment",
        label: "Comment",
        type: "Text",
        inputType: "text",
        size: "medium",
        id: "comment",
      },
    ],
  },
  transactions: {
    add: [
      {
        name: "transactionAmount",
        label: "Number of shares",
        type: "Number",
        inputType: "number",
        size: "small",
        id: "transactionAmount",
      },
      {
        name: "transactionExpense",
        label: "Amount invested",
        type: "Expense",
        // inputType: "expense",
        toggleSelections: [{ value: "EUR" }, { value: "USD" }],
        size: "small",
        id: "transactionExpense",
      },
      {
        name: "price",
        label: "Estimated price",
        type: "Disabled",
        inputType: "disabled",
        size: "small",
        id: "price",
      },
      {
        name: "type",
        label: "Type of transaction",
        type: "Dropdown",
        inputType: "select",
        menuItems: ["Buy", "Sell"],
        defaultSelect: "Buy",
        size: "small",
        id: "type",
      },
      {
        name: "date",
        label: "Date",
        type: "Date",
        inputType: "date",
        size: "medium",
        id: "date",
      },
    ],
    edit: [
      {
        name: "name",
        label: "Asset",
        type: "Text",
        inputType: "text",
        size: "medium",
        id: "name",
      },
      {
        name: "sharesAmount",
        label: "Number of shares",
        type: "Number",
        inputType: "number",
        size: "small",
        id: "sharesAmount",
      },
      {
        name: "transactionExpense",
        label: "Amount invested",
        type: "Expense",
        // inputType: "expense",
        toggleSelections: [{ value: "EUR" }, { value: "USD" }],
        size: "small",
        id: "transactionExpense",
      },
      {
        name: "price",
        label: "Purchase price",
        type: "Disabled",
        inputType: "disabled",
        size: "small",
        id: "price",
      },
      {
        name: "type",
        label: "Type",
        type: "Dropdown",
        inputType: "select",
        menuItems: ["Buy", "Sell"],
        defaultSelect: "Buy",
        size: "small",
        id: "type",
      },
      {
        name: "date",
        label: "Date",
        type: "Date",
        inputType: "date",
        size: "medium",
        id: "date",
      },
    ],
  },
  portfolio: {
    add: [
      {
        name: "name",
        label: "Name",
        type: "Asset",
        inputType: "text",
        size: "medium",
        id: "name",
      },
      {
        name: "customType",
        label: "Describe asset",
        type: "Dropdown",
        inputType: "select",
        menuItems: ["Speculation", "Dividend", "Value", "Index", "N/A"],
        defaultSelect: "N/A",
        size: "small",
        id: "customType",
      },
      {
        name: "sharesAmount",
        label: "Number of shares",
        type: "Number",
        inputType: "number",
        size: "small",
        id: "sharesAmount",
      },
      {
        name: "spent",
        label: "Amount invested",
        type: "Expense",
        toggleSelections: [{ value: "EUR" }, { value: "USD" }],
        size: "small",
        id: "spent",
      },
    ],
    edit: [
      {
        name: "name",
        label: "Asset",
        type: "Text",
        inputType: "text",
        size: "medium",
        id: "name",
      },
      {
        name: "customType",
        label: "Describe asset",
        type: "Dropdown",
        inputType: "select",
        menuItems: ["Speculation", "Dividend", "Value", "Index", "N/A"],
        defaultSelect: "N/A",
        size: "small",
        id: "customType",
      },
      {
        name: "sharesAmount",
        label: "Number of shares",
        type: "Number",
        inputType: "number",
        size: "small",
        id: "sharesAmount",
      },
      {
        name: "spent",
        label: "Amount invested",
        type: "Expense",
        toggleSelections: [{ value: "EUR" }, { value: "USD" }],
        size: "small",
        id: "spent",
      },
    ],
  },
};

export { formFields };
